# Generated by Django 6.0.7 on 2026-08-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price']},
        ),
    ]
